spring:
  main:
    allow-bean-definition-overriding: true
csv:
  defaultCurrencyRateFilePath: classpath:/templates/csv/default-currency-rates.csv
  maxUploadFileSize: 10
  maxRequestSize: 10

rootUri: /formedix